
def ler_cookies():
    cookies = [
        {
            "domain": ".sportsbet.io",
            "expirationDate": 1666121759.817572,
            "hostOnly": 'false',
            "httpOnly": 'true',
            "name": "__cf_bm",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": 'true',
            "session": 'false',
            "storeId": "0",
            "value": "ohlG4rAWsKEQ6ACAYrOhn35Nwknq835xO6fhUZdS.Uk-1666119959-0-AXr5gU+Wi601jCve7uUNq9rMX+OtnjMLeraooUkjUgc8uGPJBbjs01WRF3T6VXm4pVEu+tBAgHt1dqtFYl3cwz0=",
            "id": 1
        },
        {
            "domain": ".sportsbet.io",
            "expirationDate": 1700679685.879662,
            "hostOnly": 'false',
            "httpOnly": 'false',
            "name": "_ga",
            "path": "/",
            "sameSite": "unspecified",
            "secure": 'false',
            "session": 'false',
            "storeId": "0",
            "value": "GA1.1.1344200292.1665694877",
            "id": 2
        },
        {
            "domain": ".sportsbet.io",
            "expirationDate": 1700679958.710921,
            "hostOnly": 'false',
            "httpOnly": 'false',
            "name": "_ga_SEKFV66B0S",
            "path": "/",
            "sameSite": "unspecified",
            "secure": 'false',
            "session": 'false',
            "storeId": "0",
            "value": "GS1.1.1666119675.7.1.1666119958.45.0.0",
            "id": 3
        },
        {
            "domain": ".sportsbet.io",
            "expirationDate": 1666206085,
            "hostOnly": 'false',
            "httpOnly": 'false',
            "name": "_gid",
            "path": "/",
            "sameSite": "unspecified",
            "secure": 'false',
            "session": 'false',
            "storeId": "0",
            "value": "GA1.2.1781625145.1666113008",
            "id": 4
        },
        {
            "domain": ".sportsbet.io",
            "expirationDate": 1700679957.698008,
            "hostOnly": 'false',
            "httpOnly": 'false',
            "name": "_sp_srt_id.b17c",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": 'true',
            "session": 'false',
            "storeId": "0",
            "value": "6a65d035-8683-460b-a17e-fd06658c37ae.1665694877.6.1666119958.1666115374.3c930fc3-f3e3-4aff-84e7-65a507db93fb",
            "id": 5
        },
        {
            "domain": ".sportsbet.io",
            "expirationDate": 1666121757,
            "hostOnly": 'false',
            "httpOnly": 'false',
            "name": "_sp_srt_ses.b17c",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": 'true',
            "session": 'false',
            "storeId": "0",
            "value": "*",
            "id": 6
        },
        {
            "domain": ".sportsbet.io",
            "expirationDate": 1697655689,
            "hostOnly": 'false',
            "httpOnly": 'false',
            "name": "fs_cid",
            "path": "/",
            "sameSite": "strict",
            "secure": 'true',
            "session": 'false',
            "storeId": "0",
            "value": "1.0",
            "id": 7
        },
        {
            "domain": ".sportsbet.io",
            "expirationDate": 1697230882,
            "hostOnly": 'false',
            "httpOnly": 'false',
            "name": "fs_uid",
            "path": "/",
            "sameSite": "strict",
            "secure": 'true',
            "session": 'false',
            "storeId": "0",
            "value": "#BN5B8#6330663203213312:6460777772322816:::#/1697230882",
            "id": 8
        },
        {
            "domain": ".sportsbet.io",
            "expirationDate": 1666121482,
            "hostOnly": 'false',
            "httpOnly": 'false',
            "name": "MKTSRC",
            "path": "/",
            "sameSite": "unspecified",
            "secure": 'false',
            "session": 'false',
            "storeId": "0",
            "value": "{\"t\":1666119682458,\"d\":{\"src\":\"direct\",\"mdm\":\"direct\",\"cmp\":\"\",\"kwd\":\"\",\"cnt\":\"\",\"glc\":\"\",\"msc\":\"\"}}",
            "id": 9
        },
        {
            "domain": "sportsbet.io",
            "expirationDate": 1697380909,
            "hostOnly": 'true',
            "httpOnly": 'false',
            "name": "__tid",
            "path": "/",
            "sameSite": "unspecified",
            "secure": 'false',
            "session": 'false',
            "storeId": "0",
            "value": "uid-8882050324.5890699250",
            "id": 10
        },
        {
            "domain": "sportsbet.io",
            "expirationDate": 1666121009,
            "hostOnly": 'true',
            "httpOnly": 'false',
            "name": "_dd_s",
            "path": "/",
            "sameSite": "strict",
            "secure": 'false',
            "session": 'false',
            "storeId": "0",
            "value": "rum=1&id=6c3c2e30-4f03-4f72-ba11-1ff2d09eb095&created=1666119674521&expire=1666121009425&logs=1",
            "id": 11
        },
        {
            "domain": "sportsbet.io",
            "expirationDate": 1700679685.750877,
            "hostOnly": 'true',
            "httpOnly": 'false',
            "name": "_wingify_pc_uuid",
            "path": "/",
            "sameSite": "unspecified",
            "secure": 'false',
            "session": 'false',
            "storeId": "0",
            "value": "bb553ea264b944e194f77968315f3588",
            "id": 12
        },
        {
            "domain": "sportsbet.io",
            "hostOnly": 'true',
            "httpOnly": 'false',
            "name": "experiments",
            "path": "/",
            "sameSite": "unspecified",
            "secure": 'false',
            "session": 'true',
            "storeId": "0",
            "value": "%7B%22arLUC_zhRlKw0HignXgxRA%22%3A3%7D",
            "id": 13
        },
        {
            "domain": "sportsbet.io",
            "expirationDate": 1681665033,
            "hostOnly": 'true',
            "httpOnly": 'false',
            "name": "g_state",
            "path": "/",
            "sameSite": "unspecified",
            "secure": 'false',
            "session": 'false',
            "storeId": "0",
            "value": "{\"i_p\":1666717833229,\"i_l\":3}",
            "id": 14
        },
        {
            "domain": "sportsbet.io",
            "expirationDate": 1666121909.379112,
            "hostOnly": 'true',
            "httpOnly": 'false',
            "name": "GW_CLIENT_ID",
            "path": "/",
            "sameSite": "unspecified",
            "secure": 'false',
            "session": 'false',
            "storeId": "0",
            "value": "a957ae1a80841a17f4632aa0b2bd1d17e5c12ab76f718d612c3176e53ebd4e7e",
            "id": 15
        },
        {
            "domain": "sportsbet.io",
            "expirationDate": 1666299679,
            "hostOnly": 'true',
            "httpOnly": 'false',
            "name": "tryMetamaskHide",
            "path": "/",
            "sameSite": "unspecified",
            "secure": 'false',
            "session": 'false',
            "storeId": "0",
            "value": "'true'",
            "id": 16
        },
        {
            "domain": "sportsbet.io",
            "expirationDate": 1666724760,
            "hostOnly": 'true',
            "httpOnly": 'false',
            "name": "userPreferenceId",
            "path": "/",
            "sameSite": "unspecified",
            "secure": 'false',
            "session": 'false',
            "storeId": "0",
            "value": "U3BvcnRzYmV0UHJlZmVyZW5jZXNVc2VyUHJlZmVyZW5jZTo2MzQ4N2M5YTBkZDA3MjgxY2M4N2UxMzg=",
            "id": 17
        },
        {
            "domain": "sportsbet.io",
            "expirationDate": 1700254879.699938,
            "hostOnly": 'true',
            "httpOnly": 'false',
            "name": "wingify_donot_track_actions",
            "path": "/",
            "sameSite": "unspecified",
            "secure": 'false',
            "session": 'false',
            "storeId": "0",
            "value": "0",
            "id": 18
        }
    ]

    new_cookies = ''
    for c in cookies:
        new_cookies +=f"{c['name']}={c['value']};"
    return new_cookies
